Accordion
denali-design/denali-css pull request #189
Opened 2021-06-25 14:49 UTC by anusha-66

## In this PR:

Accordion component implemented, Initial draft
Please suggest if any thing has to be changed for it function better

---

## Screenshot(s):

**Before**

no such component existed

**After**

![image](https://user-images.githubusercontent.com/27336160/123442512-efd40580-d5a2-11eb-8006-7f9b44b43a14.png)
![image](https://user-images.githubusercontent.com/27336160/123442597-0aa67a00-d5a3-11eb-8767-7063ae6b81f4.png)

---

### Pre-Merge Checklist:

#### Reviewer # 1

- [ ] Review **Source** code.
- [ ] Review **Test** code.
- [ ] Review **Snapshot**.
- [ ] Review PR **Storybook**.

**NOTE:** To review PR **Storybook** for the last build, **download** PR storybook from CI build **Artifacts**.

#### PR Owner

- [ ] [![Build Status][status-image]][status-url] Pipeline is green.

[status-image]: https://cd.screwdriver.cd/pipelines/3067/badge
[status-url]: https://cd.screwdriver.cd/pipelines/3067

2021-06-28 16:42 UTC, chasturansky requested changes

2021-06-29 12:33 UTC, anusha-66 commented
@chasturansky 

Have modified the code w.r.t. the PR comments in commit 594c2c7
Can you please review the latest

2021-07-20 15:05 UTC, anusha-66 commented
@chasturansky 
I've made all the final changes to accordion component and have committed them in the latest commit 71d13c4
Could you please review them So that I could push accordion changes and then raise a PR on Drawer right away...

2021-07-20 22:31 UTC, chasturansky approved these changes

2021-07-21 13:41 UTC, merged